export const PRODUCTS_START_FETCH = "PRODUCTS_START_FETCH";
export const PRODUCTS_END_FETCH = "PRODUCTS_END_FETCH";
export const PRODUCTS_FETCH_ERROR = "PRODUCTS_FETCH_ERROR";
export const PRODUCTS_TOGGLE_PRODUCT_CATEGORY = "PRODUCTS_TOGGLE_PRODUCT_CATEGORY";
export const PRODUCTS_UPDATE_OFFSET = "PRODUCTS_UPDATE_OFFSET";
export const PRODUCTS_UPDATE_NB_OF_VISIBLE_PRODUCTS_LAZY_LOAD = "PRODUCTS_UPDATE_NB_OF_VISIBLE_PRODUCTS_LAZY_LOAD";
export const PRODUCTS_UPDATE_NB_OF_PRODUCTS_PER_PAGE = "PRODUCTS_UPDATE_NB_OF_PRODUCTS_PER_PAGE";
export const PRODUCTS_UPDATE_SORT_MODE = "PRODUCTS_UPDATE_SORT_MODE";

export const PRODUCTS_CATEGORIES_START_FETCH = "PRODUCTS_CATEGORIES_START_FETCH";
export const PRODUCTS_CATEGORIES_END_FETCH = "PRODUCTS_CATEGORIES_END_FETCH";
export const PRODUCTS_CATEGORIES_FETCH_ERROR = "PRODUCTS_CATEGORIES_FETCH_ERROR";

export const DROPDOWN_OPEN = "DROPDOWN_OPEN";
export const DROPDOWN_CLOSE = "DROPDOWN_CLOSE";
