export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_FETCHED = "FETCH_PRODUCTS_FETCHED";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCTS_CATEGORIES_START = "FETCH_PRODUCTS_CATEGORIES_START";
export const FETCH_PRODUCTS_CATEGORIES_FETCHED = "FETCH_PRODUCTS_CATEGORIES_FETCHED";
export const FETCH_PRODUCTS_CATEGORIES_ERROR = "FETCH_PRODUCTS_CATEGORIES_ERROR";

export const TOGGLE_PRODUCT_CATEGORY = "TOGGLE_PRODUCT_CATEGORY";

export const UPDATE_PRODUCTS_OFFSET = "UPDATE_PRODUCTS_OFFSET";
export const UPDATE_NB_OF_VISIBLE_PRODUCTS_IN_LAZY_LOAD_MODE = "UPDATE_NB_OF_VISIBLE_PRODUCTS_IN_LAZY_LOAD_MODE";
export const UPDATE_NB_OF_PRODUCTS_PER_PAGE = "UPDATE_NB_OF_PRODUCTS_PER_PAGE";
export const UPDATE_SORT_MODE = "UPDATE_SORT_MODE";

